AWSRegion: "ca-central-1"
CognitoClientID: ""
CognitoPoolID: ""
CognitoRegion: ""
DynamoAPIVersion: "2012-08-10"
DynamoRegion: "ca-central-1"
GraphqlURI: "http://10.0.1.9:4000/"
S3Bucket: "gdps-fs-dwnld"
S3FilePrefix: "reports"
SsmPath: "gdps-fs-dwnld"
Stage: "prod"